melowntech/vts-browser-js

- package.json
- src/core/core.js
- src/core/inspector/input.js
- src/core/map/draw-tiles.js
- src/core/map/geodata-processor/worker-linestring.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/renderer/draw.js
> Fixed geodata

- package.json
- src/core/core.js
- src/core/map/draw.js
- src/core/map/map.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/renderer.js
> Fixed getHitCoords

- demos/hit-surface/demo.js
- demos/meshes-hit-test/demo.js
- demos/meshes/demo.js
- package.json
- src/browser/rois/pano/pano.js
- src/browser/rois/photo/photo.js
- src/core/core.js
- src/core/inspector/inspector.js
- src/core/map/draw.js
- src/core/map/geodata-processor/worker-linestring.js
- src/core/map/geodata-processor/worker-text.js
- src/core/map/interface.js
- src/core/map/map.js
- src/core/map/mesh.js
- src/core/map/metanode.js
- src/core/map/render-slots.js
- src/core/map/surface-tile.js
- src/core/renderer/draw.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/interface.js
* depth offset for images and lines
* opacity support for meshes
* fixed grid
* fixed street names
> Depth offset for images and lines, opacity support for meshes

- package.json
- src/browser/index.js
- src/core/core.js
- src/core/index.js
- src/core/inspector/input.js
- src/core/map/draw.js
- src/core/map/measure.js
- src/core/map/metanode.js
- src/core/map/surface-tree.js
* fixed street names orientation
* fixed bbox generation
* platform module is public
> Fixed streets names orientation

- package.json
- src/browser/autopilot/autopilot.js
- src/browser/browser.js
- src/core/core.js
- src/core/inspector/layers.js
- src/core/map/draw-tiles.js
- src/core/map/metanode.js
- src/core/map/surface-tile.js
- src/core/map/surface-tree.js
- src/core/renderer/bbox.js
- src/core/renderer/camera.js
* fixed surface switching
* no autorotation when loading screen is displayed
* fixed bboxes with infinite size
> Fixed surface switching

- package.json
- src/browser/browser.js
- src/core/core.js
- src/core/map/draw-tiles.js
* better bound layers sorting
* fixed render options
> Better bound layers sorting 

- package.json
- src/browser/browser.js
- src/core/core.js
- src/core/map/draw-tiles.js
- src/core/map/draw.js
- src/core/map/geodata-processor/worker-linestring.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/map/geodata-processor/worker-polygon.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/map.js
- src/core/renderer/bbox.js
- src/core/renderer/camera.js
- src/core/renderer/draw.js
- src/core/renderer/geometry.js
- src/core/renderer/gpu/device.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/line.js
- src/core/renderer/gpu/mesh.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/gpu/text.js
- src/core/renderer/gpu/texture.js
- src/core/renderer/init.js
- src/core/renderer/interface.js
- src/core/renderer/renderer.js
- src/core/utils/url.js
* advanced hit for geodata lines
* better IE11 compatibility
> Advanced hit test for geodata

- package.json
- src/browser/browser.js
- src/browser/control-mode/map-observer.js
- src/browser/control-mode/pano.js
- src/browser/ui/control/compass.js
- src/browser/ui/control/credits.js
- src/browser/ui/control/loading.js
- src/browser/ui/control/search-filter.js
- src/browser/ui/control/search.js
- src/browser/ui/control/space.js
- src/browser/ui/control/zoom.js
- src/core/core.js
- src/core/inspector/graphs.js
- src/core/inspector/input.js
* search determines view extent for selected location
* search results filtering
> Better search

- package.json
- src/browser/ui/control/search.js
- src/core/core.js
* better view extent determination
> Better search results

- package.json
- src/core/core.js
- src/core/inspector/stylesheets.js
- src/core/map/stylesheet.js
- src/core/map/surface.js
- src/core/map/texture.js
* fixed bound layer masks
* fixed style paths
> Fixed bound layer masks and fixed style paths

- package.json
- src/browser/ui/control/search.js
- src/core/core.js
- src/core/inspector/layers.js
- src/core/inspector/stylesheets.js
- src/core/map/draw-tiles.js
- src/core/map/metanode.js
- src/core/map/texture.js
* new bound layer sorting
* fixed double click on search bar
* fixed css in stylesheet inspector
* fixed tile conus angle
> New bound layer shorting

- package.json
- src/core/core.js
- src/core/inspector/input.js
- src/core/map/draw.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/map/geodata-processor/worker-style.js
- src/core/renderer/draw.js
- src/core/renderer/gpu/group.js
- src/core/renderer/renderer.js
- src/core/renderer/rmap.js
* geodata styles support label-no-overlap
* geodata styles support label-no-overlap-margin
> Geodata styles support label-no-overlap

- package.json
- src/core/core.js
- src/core/map/geodata-builder.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/interface.js
> Geodata builder

- demos/geodata-advanced-hover/demo.js
- demos/geodata-advanced-hover/index.html
- demos/geodata-basic/demo.js
- demos/geodata-with-dynamic-render/demo.js
- demos/gpx-viewer/demo.js
- demos/gpx-viewer/index.html
- demos/index.html
- package.json
- src/browser/ui/element/event.js
- src/core/core.js
- src/core/map/geodata-builder.js
- src/core/map/geodata-geometry.js
- src/core/map/geodata-processor/worker-linestring.js
- src/core/map/interface.js
- src/core/map/map.js
* gpx viewer demo
* advanced hover demo
* fixed geometries
* fixed hit test
* fixed geodata events
> Gpx viewer demo

- demos/geodata-hover-events/demo.js
- demos/geodata-hover-events/index.html
- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-main.js
* fixed geodata hit test
* new geodata hover events demo
> Fixed geodata hit test

- demos/index.html
- package.json
- src/core/core.js
- src/core/map/draw.js
- src/core/map/geodata-processor/worker-linestring.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/geodata-view.js
- src/core/map/mesh.js
- src/core/renderer/draw.js
- src/core/renderer/gpu/device.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/program.js
- src/core/renderer/interface.js
- src/core/renderer/renderer.js
- src/core/utils/utils.js
* fixed geodata stats
* better shader error handling
* better demos index
* fixed geodata style processing
> Fixed geodata stats

- package.json
- src/browser/browser.js
- src/browser/ui/control/loading.js
- src/browser/ui/control/search-filter.js
- src/browser/ui/control/search.js
- src/core/core.js
- src/core/map/draw.js
- src/core/map/geodata-geometry.js
- src/core/map/geodata-import/vts-geodata.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/map/map.js
- src/core/map/mesh.js
- src/core/map/surface-tile.js
- src/core/renderer/draw.js
- src/core/renderer/gpu/shaders.js
* mars atmosphere support
* fixed geodata events
> Mars atmosphere support

- package.json
- src/browser/browser.js
- src/browser/control-mode/map-observer.js
- src/core/core.js
- src/core/inspector/input.js
- src/core/map/camera.js
- src/core/map/convert.js
- src/core/map/draw.js
- src/core/map/interface.js
- src/core/renderer/gpu/texture.js
- src/core/utils/utils.js
* gpu cache limit increased
* better tilt threshold
* better navigation in subjective mode
* rescaling of non power of two textures
* support for shifted camera near plane in subjective mode
* fixed atmosphere
> Gpu cache limit increased

- demos/geodata-click-and-hover-events/demo.js
- demos/geodata-click-and-hover-events/index.html
- demos/geodata-click-events/demo.js
- demos/geodata-click-events/index.html
- package.json
- src/core/core.js
- src/core/map/camera.js
- src/core/map/draw.js
- src/core/map/geodata-processor/worker-globals.js
- src/core/map/geodata-processor/worker-linestring.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/interface.js
- src/core/map/map.js
- src/core/map/mesh.js
- src/core/renderer/draw.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/renderer.js
* geodata supports selection layer, label/icon sticks
* gedata styles support selected-hover-events
* advanced string functions + round, floor, ceil for geodadata styles
* fixed rendering on mobile devices
> Geodata supports selection layer, label/icon sticks, fixed rendering on mobile devices

- package.json
- src/browser/ui/control/credits.js
- src/browser/ui/control/loading.js
- src/browser/ui/ui.js
- src/core/core.js
- src/core/map/convert.js
- src/core/map/geodata-builder.js
- src/core/map/geodata-geometry.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/map/interface.js
- src/core/map/map.js
- src/core/map/measure.js
- src/core/map/position.js
- src/core/map/srs.js
- src/core/map/surface-tree.js
- src/core/renderer/draw.js
- src/core/renderer/gpu/font.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/init.js
- src/core/utils/utils.js
* more accurate terrain heights
* new coordinate conversions
* fixed credits and events
* optimalizations
> More accurate terrain heights

- package.json
- src/core/core.js
- src/core/map/draw.js
- src/core/map/interface.js
- src/core/map/map.js
- src/core/renderer/init.js
- src/core/renderer/renderer.js
- src/core/utils/utils.js
* new way of making screenshots
> New way of making screenshots

- package.json
- src/browser/ui/control/search-filter.js
- src/browser/ui/control/search.js
- src/core/core.js
- src/core/renderer/draw.js
- src/core/renderer/rmap.js
- better label visibility solver
- better search results
> Better label visibility solver

- demos/meshes-obj-import/modelObj.js
- package.json
- src/browser/ui/control/credits.js
- src/core/core.js
- src/core/map/geodata-processor/worker-font.js
- src/core/map/geodata-processor/worker-globals.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-style.js
- src/core/renderer/rmap.js
* faster geodata style processing
* faster text generation
> Faster geodata style processing

- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-style.js
> Fixed vswitch

- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-style.js
> Fixed label stick

- package.json
- src/browser/ui/control/measure.js
- src/core/core.js
- src/core/map/config.js
- src/core/map/geodata-processor/processor.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/map.js
- src/core/renderer/draw.js
- src/core/renderer/gmap.js
- src/core/renderer/gpu/group.js
* faster hysteresis
* stable vswitch
* fixed legacy mode
* fixed area measure
* new clamp function in styles
> Faster hysteresis

- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-globals.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-message.js
- src/core/map/geodata-view.js
- src/core/map/map.js
- src/core/renderer/gpu/group.js
> Fixed geodata processing

- package.json
- src/core/core.js
- src/core/inspector/input.js
- src/core/map/draw.js
- src/core/map/geodata-processor/processor.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/geodata-view.js
- src/core/map/map.js
- src/core/map/surface-tile.js
- src/core/map/surface-tree.js
- src/core/renderer/camera.js
- src/core/renderer/draw.js
- src/core/renderer/gmap.js
- src/core/renderer/gpu/device.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/texture.js
- src/core/renderer/renderer.js
* new scr-count mode
* no overlap for icons
* label stick modes
* fixed min,max functions
* fixed gpu state switching
* fixed config params
> New scr-count mode

- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-style.js
> Fixed geodata style parsing

- package.json
- src/core/core.js
- src/core/map/camera.js
- src/core/map/map.js
- src/core/map/measure.js
- src/core/renderer/gpu/device.js
* fixed view switching
* fixed terrain height processing
> Fixed view switching

- package.json
- src/core/core.js
- src/core/inspector/layers.js
- src/core/map/draw-tiles.js
- src/core/map/draw.js
- src/core/map/geodata-processor/processor.js
- src/core/map/geodata-processor/worker-globals.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-message.js
- src/core/map/geodata-view.js
- src/core/map/geodata.js
- src/core/map/interface.js
- src/core/map/loader/loader.js
- src/core/map/loader/worker-globals.js
- src/core/map/loader/worker-main.js
- src/core/map/loader/worker-mesh.js
- src/core/map/map.js
- src/core/map/mesh.js
- src/core/map/metatile.js
- src/core/map/submesh.js
- src/core/map/subtexture.js
- src/core/map/surface-tree.js
* loading resources in worker
* parsing mesh in worker
> Loading resources in worker, parsing mesh in worker

- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-globals.js
- src/core/map/geodata-processor/worker-main.js
> Fixed geodata on ie11, edge

- package.json
- src/core/core.js
- src/core/map/geodata.js
- src/core/map/loader/worker-main.js
- src/core/map/loader/worker-mesh.js
- src/core/map/mesh.js
> Fixed resource cache

- package.json
- src/core/core.js
- src/core/inspector/input.js
- src/core/map/camera.js
- src/core/map/draw.js
- src/core/map/geodata-view.js
- src/core/map/geodata.js
- src/core/map/mesh.js
- src/core/map/stylesheet.js
- src/core/map/submesh.js
- src/core/map/subtexture.js
- src/core/renderer/gpu/font.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/line.js
- src/core/renderer/gpu/mesh.js
- src/core/renderer/gpu/pixel-line3.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/gpu/texture.js
- src/core/renderer/init.js
- src/core/renderer/renderer.js
* fixed gpu cache
* super elevation mode
> Fixed GPU Cache

- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-font.js
- src/core/renderer/interface.js
> Fixed text rendering

- README.md
- package.json
- src/browser/control-mode/map-observer.js
- src/browser/ui/control/measure-lite.js
- src/browser/ui/control/measure.js
- src/browser/ui/element/element.js
- src/core/core.js
- src/core/inspector/input.js
- src/core/map/camera.js
- src/core/map/config.js
- src/core/map/convert.js
- src/core/map/draw-tiles.js
- src/core/map/geodata-view.js
- src/core/map/interface.js
- src/core/map/map.js
- src/core/map/mesh.js
- src/core/map/metanode.js
- src/core/map/submesh.js
- src/core/map/surface-tile.js
- src/core/map/surface-tree.js
- src/core/map/surface.js
- src/core/map/view.js
- src/core/renderer/draw.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/mesh.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/init.js
- src/core/renderer/renderer.js
- src/core/utils/utils.js
* super elevation support
* fixed double click outside map
* fixed cursor in measuring tools
* generalized gpu shaders
> Super elevation support

- package.json
- src/browser/index.js
- src/core/core.js
- src/core/inspector/input.js
- src/core/map/draw.js
- src/core/map/geodata-builder.js
- src/core/map/geodata-import/geojson.js
- src/core/map/geodata-processor/processor.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-message.js
- src/core/map/geodata-processor/worker-pointarray.js
- src/core/map/geodata-processor/worker-polygon.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/geodata-processor/worker-text.js
- src/core/map/mesh.js
- src/core/renderer/draw.js
- src/core/renderer/gmap.js
- src/core/renderer/gpu/device.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/init.js
- src/core/renderer/renderer.js
- webpack.config.js
* scr-count8
* geodata models with flat shade support
* geojson supports polygons
* new properties for geodata polygons
* new function for geodata styles
* public dom api
* fixed webgl errors
> Support for geodata models

- package.json
- src/core/core.js
- src/core/map/draw.js
- src/core/map/geodata-processor/processor.js
- src/core/map/geodata-processor/worker-globals.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/map.js
- src/core/map/mesh.js
- src/core/renderer/gpu/texture.js
- src/core/renderer/init.js
- src/core/renderer/renderer.js
* fixed flatshade on mobile devices
* language support in styles
* new string functions in styles
* faster visibility mode
> fixed flatshade on mobile devices

- package.json
- src/core/core.js
- src/core/renderer/init.js
* fixed visibility test on mobile devices
> fixed visibility test on mobile devices

- src/core/map/geodata-builder.js
Fix issue #160: addPolygon3 exception caused by uninitialized proj in webmercator mode.
> Fix issue #160: addPolygon3 fails in webmercator projection 

- package.json
- src/core/core.js
- src/core/inspector/stats.js
- src/core/map/draw.js
- src/core/map/geodata-processor/processor.js
- src/core/map/geodata-processor/worker-globals.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/map.js
- src/core/map/surface-tree.js
- src/core/renderer/draw.js
- src/core/renderer/gmap.js
- src/core/renderer/rmap.js
* benevolent mode for labels
* reduce mode stats
* fixed scr-count8
* new system variables for geodata styles
> New system variables for geodata styles

- package.json
- src/core/core.js
- src/core/map/geodata-processor/worker-linestring.js
- src/core/map/map.js
- src/core/map/surface-tree.js
* fixed dynamic labels
* support for maxLod parameter in map view
> Fixed dynamic labels, support for maxLod parameter in map view

- package.json
- src/core/core.js
- src/core/inspector/input.js
- src/core/inspector/stats.js
- src/core/map/mesh.js
- src/core/map/stats.js
- src/core/map/submesh.js
* new texels per polygon stats
> Texels per polygon stats

- package.json
- src/core/core.js
- src/core/renderer/draw.js
- src/core/renderer/renderer.js
- src/core/renderer/rmap.js
* fixed dynamic labels size
* optimized render buffer switching
> Fixed dynamic labels size

- src/browser/browser.js
- src/browser/ui/control/search-filter.js
- src/browser/ui/control/search.js
- src/core/core.js
- src/core/map/geodata-builder.js
* fixed search path
* more robust height coding
> Fixed search

- demos/switching-geodata/demo.js
- package.json
- src/browser/browser.js
- src/browser/control-mode/map-observer.js
- src/core/core.js
- src/core/inspector/input.js
- src/core/inspector/stats.js
- src/core/map/draw-tiles.js
- src/core/map/draw.js
- src/core/map/geodata-builder.js
- src/core/map/geodata-import/3dtiles.js
- src/core/map/geodata-import/vts-geodata.js
- src/core/map/geodata-processor/worker-main.js
- src/core/map/geodata-processor/worker-parser.js
- src/core/map/geodata-processor/worker-style.js
- src/core/map/geodata-view.js
- src/core/map/geodata.js
- src/core/map/map.js
- src/core/map/mesh.js
- src/core/map/subtexture.js
- src/core/map/surface-tree.js
- src/core/renderer/gpu/group.js
- src/core/renderer/gpu/program.js
- src/core/renderer/gpu/shaders.js
- src/core/renderer/init.js
- src/core/renderer/interface.js
- src/core/utils/url.js
- webpack.config.js
* faster loading (mesh splitting)
* geodata support meshes
* support for geodata octrees
* walk mode
* fixed heigth mode
* fixed geodata polygons
> Faster loading
